### PR TITLE
Fix deprecated Gradle plugins, bottom app bar visibility, and add-to-…

### PR DESCRIPTION
**Pull request by RotRot-pi**
Fix deprecated Gradle plugins, bottom app bar visibility, and add-to-cart button positioning

### CODE REVIEW

**Comment by RotRot-pi** [comment]
Hi @SinaSys ,
Can i ask why the pull request was closed?

**Comment by SinaSys** [comment]
Hello  @RotRot-pi 

I hope this message finds you well.

Thank you for your recent contributions to the project. Your changes (*Fix
deprecated Gradle plugins, bottom app bar visibility, and add-to-*) have
been successfully merged, and you can now see them reflected in the main
branch. Additionally, your name has been added to the contributors section.

Regarding the specific commit titled *"**Add screenshot demonstrating UI
changes,"* it was not merged because the issue it addressed was resolved by
changing the value of the useMaterial3 flag to false.

**Comment by RotRot-pi** [comment]
Thank you for the clarification, @SinaSys. I apologize for the confusion - I'm new to GitHub and open source contributions, so I misunderstood when I saw the pull request was closed.
I appreciate you merging my changes and adding me to the contributors section. Regarding the improvements I made:

- Fixing deprecated imperative apply of Flutter's Gradle plugins
- Adjusting the Bottom App Bar

Would you like me to implement these changes in your other `flutter_japanese_restaurant_app` branches as well (bloc ,cubit, provider)? 
If so, please let me know, and I'd be happy to create pull requests for them.
Thank you again for your guidance and for maintaining this project.

**Comment by SinaSys** [comment]
> Thank you for the clarification, @SinaSys. I apologize for the confusion - I'm new to GitHub and open source contributions, so I misunderstood when I saw the pull request was closed. I appreciate you merging my changes and adding me to the contributors section. Regarding the improvements I made:
> 
> * Fixing deprecated imperative apply of Flutter's Gradle plugins
> * Adjusting the Bottom App Bar
> 
> Would you like me to implement these changes in your other `flutter_japanese_restaurant_app` branches as well (bloc ,cubit, provider)? If so, please let me know, and I'd be happy to create pull requests for them. Thank you again for your guidance and for maintaining this project.

Thank you for your message and for contributing to the project. There is no need to apologize. I value your efforts and understand that getting familiar with GitHub and open-source contributions can be a learning process.

I appreciate your initiative to fix the deprecated imperative apply of Flutter's Gradle plugins and adjust the Bottom App Bar. These enhancements are beneficial to the project, and I would indeed welcome similar updates in the other branches of the flutter_japanese_restaurant_app repository, including the bloc, cubit, and provider branches. 

Please feel free to create pull requests for these branches, and I will merge them at my earliest convenience.

**Pull request closed without merging**
